# overlays/dev/kustomization.yaml
namespace: ambiente-dev-encuestapp-mern-ECMAScript6

resources:
  - ../../base

patchesStrategicMerge:
  - patch-back-deployment.yaml
  - patch-front-deployment.yaml
