apiVersion: apps/v1
kind: Deployment
metadata:
  name: encuestapp
spec:
  template:
    spec:
      containers:
        - name: encuestapp
          image: emi8977/frontend-encuestapp-mern-ecmascript6:dev-83c01ee
