# overlays/prod/kustomization.yaml
namespace: ambiente-prod-encuestapp-mern-ECMAScript6
resources:
  - ../../base
  #- hpa.yaml
  #- networkpolicy.yaml
  #- pdb.yaml

patchesStrategicMerge:
  - patch-deployment.yaml
  - patch-secret.yaml

