apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  template:
    spec:
      containers:
        - name: backend
          image: emi8977/backend-encuestapp-mern-ecmascript6:REPLACEME

