apiVersion: apps/v1
kind: Deployment
metadata:
  name: encuestapp
spec:
  template:
    spec:
      containers:
        - name: encuestapp
          image: emi8977/backend-encuestapp-mern-ecmascript6:REPLACEME

